#include "stdafx.h"
#include "ToolsUiManager.h"
#include "imgui.h"
#include "FileSystem.h"

//////////////////////////////////////////////////////////////////////////

ToolsUiManager gToolsUiManager;

//////////////////////////////////////////////////////////////////////////

// imgui specific data size constants
const unsigned int Sizeof_ImGuiVertex = sizeof(ImDrawVert);
const unsigned int Sizeof_ImGuiIndex = sizeof(ImDrawIdx);

//////////////////////////////////////////////////////////////////////////

bool ToolsUiManager::Initialize()
{
    // initialize imgui context
    IMGUI_CHECKVERSION();

    ImGui::CreateContext();

    ImGuiIO& io = ImGui::GetIO();
    io.IniFilename = nullptr; // disable saving state
    io.LogFilename = nullptr; // disable saving log

    io.KeyMap[ImGuiKey_Tab]         = KEYCODE_TAB;
    io.KeyMap[ImGuiKey_LeftArrow]   = KEYCODE_LEFT;
    io.KeyMap[ImGuiKey_RightArrow]  = KEYCODE_RIGHT;
    io.KeyMap[ImGuiKey_UpArrow]     = KEYCODE_UP;
    io.KeyMap[ImGuiKey_DownArrow]   = KEYCODE_DOWN;
    io.KeyMap[ImGuiKey_PageUp]      = KEYCODE_PAGE_UP;
    io.KeyMap[ImGuiKey_PageDown]    = KEYCODE_PAGE_DOWN;
    io.KeyMap[ImGuiKey_Home]        = KEYCODE_HOME;
    io.KeyMap[ImGuiKey_End]         = KEYCODE_END;
    io.KeyMap[ImGuiKey_Insert]      = KEYCODE_INSERT;
    io.KeyMap[ImGuiKey_Delete]      = KEYCODE_DELETE;
    io.KeyMap[ImGuiKey_Backspace]   = KEYCODE_BACKSPACE;
    io.KeyMap[ImGuiKey_Space]       = KEYCODE_SPACE;
    io.KeyMap[ImGuiKey_Enter]       = KEYCODE_ENTER;
    io.KeyMap[ImGuiKey_Escape]      = KEYCODE_ESCAPE;

    io.BackendRendererName = "imgui_impl_impsengine";
    io.BackendFlags = ImGuiBackendFlags_HasSetMousePos;
    io.ConfigFlags = ImGuiConfigFlags_NavEnableSetMousePos;

    SetupStyle(io);

    if (AddFontFromExternalFile(io, "fonts/cousine_regular.ttf", 17.0f))
    {
        Point2D fontTextureDimensions;
        unsigned char *fontPixels;

        io.Fonts->Build();
        io.Fonts->GetTexDataAsRGBA32(&fontPixels, &fontTextureDimensions.x, &fontTextureDimensions.y);

        mFontTexture = gRenderDevice.CreateTexture2D(fontTextureDimensions, ePixelFormat_RGBA8, fontPixels, eTextureFiltering_Bilinear, eTextureRepeating_ClampToEdge);
        if (!mFontTexture)
        {
            cxx_assert(false);
        }
    }
    else
    {
        cxx_assert(false);
    }

    mVerticesBuffer = gRenderDevice.CreateVertexBuffer(eBufferUsage_Dynamic, 1024);
    cxx_assert(mVerticesBuffer);

    if (mVerticesBuffer)
    {
        mVerticesBuffer->ConfigureVertexDefinitions(Vertex2D_Format::Get());
    }

    mIndicesBuffer = gRenderDevice.CreateIndexBuffer(eBufferUsage_Dynamic, 1024);
    cxx_assert(mIndicesBuffer);

    if (mFontTexture)
    {
        GpuTexture2D* texture = mFontTexture.get();
        io.Fonts->TexID = texture;
    }

    return mVerticesBuffer && mIndicesBuffer;
}

void ToolsUiManager::Shutdown()
{
    mIndicesBuffer.reset();
    mVerticesBuffer.reset();
    mFontTexture.reset();

    if (!IsInitialized())
        return;

    ImGuiIO& io = ImGui::GetIO();

    // reset font
    io.Fonts->TexID = nullptr;

    ImGui::DestroyContext();
}

bool ToolsUiManager::IsInitialized() const
{
    return ImGui::GetCurrentContext() != nullptr;
}

void ToolsUiManager::RenderFrame()
{
    ImDrawData* imGuiDrawData = ImGui::GetDrawData();

    // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
    int fb_width = (int)(imGuiDrawData->DisplaySize.x * imGuiDrawData->FramebufferScale.x);
    int fb_height = (int)(imGuiDrawData->DisplaySize.y * imGuiDrawData->FramebufferScale.y);
    if (fb_width <= 0 || fb_height <= 0)
        return;

    ImVec2 clip_off = imGuiDrawData->DisplayPos;         // (0,0) unless using multi-viewports
    ImVec2 clip_scale = imGuiDrawData->FramebufferScale; // (1,1) unless using retina display which are often (2,2)

    // imgui primitives rendering
    for (int iCommandList = 0; iCommandList < imGuiDrawData->CmdListsCount; ++iCommandList)
    {
        const ImDrawList* cmd_list = imGuiDrawData->CmdLists[iCommandList];
        // vertex / index buffer generated by Dear ImGui

        if (!mVerticesBuffer->Create(eBufferUsage_Dynamic, cmd_list->VtxBuffer.size_in_bytes(), cmd_list->VtxBuffer.Data))
        {
            cxx_assert(false);
        }

        if (!mIndicesBuffer->Create(eBufferUsage_Dynamic, cmd_list->IdxBuffer.size_in_bytes(), cmd_list->IdxBuffer.Data))
        {
            cxx_assert(false);
        }

        gRenderDevice.BindVertexBuffer(mVerticesBuffer.get());
        gRenderDevice.BindIndexBuffer(mIndicesBuffer.get());

        for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.Size; ++cmd_i)
        {
            const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
            if (pcmd->UserCallback)
            {
                pcmd->UserCallback(cmd_list, pcmd);
                continue;
            }

            // Project scissor/clipping rectangles into framebuffer space
            float clip_rect_x = (pcmd->ClipRect.x - clip_off.x) * clip_scale.x;
            float clip_rect_y = (pcmd->ClipRect.y - clip_off.y) * clip_scale.y;
            float clip_rect_w = (pcmd->ClipRect.z - clip_off.x) * clip_scale.x;
            float clip_rect_h = (pcmd->ClipRect.w - clip_off.y) * clip_scale.y;

            bool should_draw = (clip_rect_x < fb_width && clip_rect_y < fb_height && clip_rect_w >= 0.0f && clip_rect_h >= 0.0f);
            if (!should_draw)
                continue;

            Rect2D rcClip {
                static_cast<int>(clip_rect_x), static_cast<int>(fb_height - clip_rect_h), 
                static_cast<int>(clip_rect_w - clip_rect_x), 
                static_cast<int>(clip_rect_h - clip_rect_y)
            };

            GpuTexture2D* bindTexture = static_cast<GpuTexture2D*>(pcmd->TextureId);
            gRenderDevice.BindTexture2D(eTextureUnit_0, bindTexture);

            gRenderDevice.SetScissorRect(rcClip);
            unsigned int idxBufferOffset = Sizeof_ImGuiIndex * pcmd->IdxOffset;

            eIndicesType indicesType = Sizeof_ImGuiIndex == 2 ? eIndicesType_i16 : eIndicesType_i32;
            gRenderDevice.RenderIndexedPrimitives(ePrimitiveType_Triangles, indicesType, idxBufferOffset, pcmd->ElemCount);
        }
    }
}

void ToolsUiManager::UpdateFrame(float deltaTime)
{
    ImGuiIO& io = ImGui::GetIO();

    Point2D screenSize = gRenderDevice.GetScreenResolution();
    io.DeltaTime = deltaTime; // set the time elapsed since the previous frame (in seconds)
    io.DisplaySize.x = screenSize.x * 1.0f;
    io.DisplaySize.y = screenSize.y * 1.0f;

    Point2D mousePosition = gInputs.GetMousePosition();

    io.MousePos.x = mousePosition.x * 1.0f;
    io.MousePos.y = mousePosition.y * 1.0f;
    io.MouseDown[0] = gInputs.GetMouseLeftButton();  // set the mouse button states
    io.MouseDown[1] = gInputs.GetMouseRightButton();
    io.MouseDown[3] = gInputs.GetMouseMiddleButton();

    ImGui::NewFrame();

    if (false)
    {
        ImGui::ShowDemoWindow();
    }

    for (ToolsUi* currWindow: mUiList)
    {
        if (!currWindow->IsActive()) continue;

        currWindow->DoUI(io, deltaTime);
    }

    ImGui::Render();
}

void ToolsUiManager::InputEvent(MouseButtonInputEvent& inputEvent)
{
    ImGuiIO& io = ImGui::GetIO();

    if (io.WantCaptureMouse)
    {
        inputEvent.SetConsumed();
    }
}

void ToolsUiManager::InputEvent(MouseMovedInputEvent& inputEvent)
{
    ImGuiIO& io = ImGui::GetIO();

    if (io.WantCaptureMouse)
    {
        inputEvent.SetConsumed();
    }
}

void ToolsUiManager::InputEvent(MouseScrollInputEvent& inputEvent)
{
    ImGuiIO& io = ImGui::GetIO();

    io.MouseWheelH += inputEvent.mScrollX * 1.0f;
    io.MouseWheel += inputEvent.mScrollY * 1.0f;

    if (io.WantCaptureMouse)
    {
        inputEvent.SetConsumed();
    }
}

void ToolsUiManager::InputEvent(KeyInputEvent& inputEvent)
{
    ImGuiIO& io = ImGui::GetIO();

    io.KeysDown[inputEvent.mKeycode] = inputEvent.mPressed;
    io.KeyCtrl = inputEvent.HasModifiers(KEYMOD_CTRL);
    io.KeyShift = inputEvent.HasModifiers(KEYMOD_SHIFT);
    io.KeyAlt = inputEvent.HasModifiers(KEYMOD_ALT);

    if (io.WantCaptureKeyboard)
    {
        inputEvent.SetConsumed();
    }
}

void ToolsUiManager::InputEvent(KeyCharEvent& inputEvent)
{
    ImGuiIO& io = ImGui::GetIO();

    io.AddInputCharacter(inputEvent.mUnicodeChar);

    if (io.WantTextInput)
    {
        inputEvent.SetConsumed();
    }
}

void ToolsUiManager::RegisterUi(ToolsUi* ui)
{
    cxx_assert(ui);
    if (cxx::contains(mUiList, ui)) return;

    mUiList.push_back(ui);
}

void ToolsUiManager::UnregisterUi(ToolsUi* ui)
{
    cxx_assert(ui);

    cxx::erase_elements(mUiList, ui);
}

bool ToolsUiManager::AddFontFromExternalFile(ImGuiIO& imguiIO, const char* fontFile, float fontSize)
{
    bool isSuccess = false;

    cxx::uniqueptr<BinaryInputStream> fileStream = gFiles.OpenBinaryFile(fontFile);
    if (fileStream)
    {
        long fileStreamLength = fileStream->GetLength();
        if (fileStreamLength > 0)
        {
            void* dataBuffer = IM_ALLOC(fileStreamLength);

            long readBytes = fileStream->ReadData(dataBuffer, fileStreamLength);
            cxx_assert(readBytes == fileStreamLength);

            ImFont* imFont = imguiIO.Fonts->AddFontFromMemoryTTF(dataBuffer, fileStreamLength, fontSize);
            if (imFont)
            {
                isSuccess = true;
            }
            cxx_assert(imFont);
        }
    }
    return isSuccess;
}

void ToolsUiManager::SetupStyle(ImGuiIO& imguiIO)
{
    //ImGui::StyleColorsDark();
    ImGuiStyle & style = ImGui::GetStyle();
    ImVec4 * colors = style.Colors;

    /// 0 = FLAT APPEARENCE
    /// 1 = MORE "3D" LOOK
    int is3D = 1;

    colors[ImGuiCol_Text]                   = ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
    colors[ImGuiCol_TextDisabled]           = ImVec4(0.40f, 0.40f, 0.40f, 1.00f);
    colors[ImGuiCol_ChildBg]                = ImVec4(0.25f, 0.25f, 0.25f, 1.00f);
    colors[ImGuiCol_WindowBg]               = ImVec4(0.25f, 0.25f, 0.25f, 1.00f);
    colors[ImGuiCol_PopupBg]                = ImVec4(0.25f, 0.25f, 0.25f, 1.00f);
    colors[ImGuiCol_Border]                 = ImVec4(0.12f, 0.12f, 0.12f, 0.71f);
    colors[ImGuiCol_BorderShadow]           = ImVec4(1.00f, 1.00f, 1.00f, 0.06f);
    colors[ImGuiCol_FrameBg]                = ImVec4(0.42f, 0.42f, 0.42f, 0.54f);
    colors[ImGuiCol_FrameBgHovered]         = ImVec4(0.42f, 0.42f, 0.42f, 0.40f);
    colors[ImGuiCol_FrameBgActive]          = ImVec4(0.56f, 0.56f, 0.56f, 0.67f);
    colors[ImGuiCol_TitleBg]                = ImVec4(0.19f, 0.19f, 0.19f, 1.00f);
    colors[ImGuiCol_TitleBgActive]          = ImVec4(0.22f, 0.22f, 0.22f, 1.00f);
    colors[ImGuiCol_TitleBgCollapsed]       = ImVec4(0.17f, 0.17f, 0.17f, 0.90f);
    colors[ImGuiCol_MenuBarBg]              = ImVec4(0.335f, 0.335f, 0.335f, 1.000f);
    colors[ImGuiCol_ScrollbarBg]            = ImVec4(0.24f, 0.24f, 0.24f, 0.53f);
    colors[ImGuiCol_ScrollbarGrab]          = ImVec4(0.41f, 0.41f, 0.41f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabHovered]   = ImVec4(0.52f, 0.52f, 0.52f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabActive]    = ImVec4(0.76f, 0.76f, 0.76f, 1.00f);
    colors[ImGuiCol_CheckMark]              = ImVec4(0.65f, 0.65f, 0.65f, 1.00f);
    colors[ImGuiCol_SliderGrab]             = ImVec4(0.52f, 0.52f, 0.52f, 1.00f);
    colors[ImGuiCol_SliderGrabActive]       = ImVec4(0.64f, 0.64f, 0.64f, 1.00f);
    colors[ImGuiCol_Button]                 = ImVec4(0.54f, 0.54f, 0.54f, 0.35f);
    colors[ImGuiCol_ButtonHovered]          = ImVec4(0.52f, 0.52f, 0.52f, 0.59f);
    colors[ImGuiCol_ButtonActive]           = ImVec4(0.76f, 0.76f, 0.76f, 1.00f);
    colors[ImGuiCol_Header]                 = ImVec4(0.38f, 0.38f, 0.38f, 1.00f);
    colors[ImGuiCol_HeaderHovered]          = ImVec4(0.47f, 0.47f, 0.47f, 1.00f);
    colors[ImGuiCol_HeaderActive]           = ImVec4(0.76f, 0.76f, 0.76f, 0.77f);
    colors[ImGuiCol_Separator]              = ImVec4(0.000f, 0.000f, 0.000f, 0.137f);
    colors[ImGuiCol_SeparatorHovered]       = ImVec4(0.700f, 0.671f, 0.600f, 0.290f);
    colors[ImGuiCol_SeparatorActive]        = ImVec4(0.702f, 0.671f, 0.600f, 0.674f);
    colors[ImGuiCol_ResizeGrip]             = ImVec4(0.26f, 0.59f, 0.98f, 0.25f);
    colors[ImGuiCol_ResizeGripHovered]      = ImVec4(0.26f, 0.59f, 0.98f, 0.67f);
    colors[ImGuiCol_ResizeGripActive]       = ImVec4(0.26f, 0.59f, 0.98f, 0.95f);
    colors[ImGuiCol_PlotLines]              = ImVec4(0.61f, 0.61f, 0.61f, 1.00f);
    colors[ImGuiCol_PlotLinesHovered]       = ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
    colors[ImGuiCol_PlotHistogram]          = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogramHovered]   = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_TextSelectedBg]         = ImVec4(0.73f, 0.73f, 0.73f, 0.35f);
    colors[ImGuiCol_ModalWindowDimBg]       = ImVec4(0.80f, 0.80f, 0.80f, 0.35f);
    colors[ImGuiCol_DragDropTarget]         = ImVec4(1.00f, 1.00f, 0.00f, 0.90f);
    colors[ImGuiCol_NavHighlight]           = ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
    colors[ImGuiCol_NavWindowingHighlight]  = ImVec4(1.00f, 1.00f, 1.00f, 0.70f);
    colors[ImGuiCol_NavWindowingDimBg]      = ImVec4(0.80f, 0.80f, 0.80f, 0.20f);

    style.PopupRounding     = 3;
    style.WindowPadding     = ImVec2(4, 4);
    style.FramePadding      = ImVec2(6, 4);
    style.ItemSpacing       = ImVec2(6, 2);
    style.ScrollbarSize     = 15;
    style.WindowBorderSize  = 1;
    style.ChildBorderSize   = 1;
    style.PopupBorderSize   = 1;
    style.IndentSpacing     = 22.0f;
    style.FrameBorderSize   = is3D * 1.0f; 
    style.WindowRounding    = 2;
    style.ChildRounding     = 2;
    style.FrameRounding     = 2;
    style.ScrollbarRounding = 2;
    style.GrabRounding      = 2;
    style.TabBorderSize     = is3D * 1.0f; 
    style.TabRounding       = 2;
}
