#pragma once

#define GAME_VERSION_MAJOR  0
#define GAME_VERSION_MINOR  1
#define GAME_VERSION_BUILD  0
#define GAME_VERSION_TAG    "dev.8"

#define STRINGIZE_NX(A) #A
#define STRINGIZE(A) STRINGIZE_NX(A)

#define GAME_TITLE "GLKeeper"
#define GAME_VERSION_STRING \
    STRINGIZE(GAME_VERSION_MAJOR) "." \
    STRINGIZE(GAME_VERSION_MINOR) "." \
    STRINGIZE(GAME_VERSION_BUILD) "-" GAME_VERSION_TAG
#define GAME_TITLE_VER GAME_TITLE " " GAME_VERSION_STRING
